version: '3'

services:

  db:
    container_name: db
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - ./database_dumps:/app/database_dumps

  web:
    container_name: web
    build: .
    volumes:
      - ./etna:/app/etna
      - ./config:/app/config
      - ./sass:/app/sass
      - ./scripts:/app/scripts
      - ./static:/app/static
      - ./templates:/app/templates
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - media:/media
    depends_on:
      - db
    ports:
      - 8000:8080
    command: sh /app/bash/run-dev.sh
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - ENVIRONMENT=develop
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@tna-development.fake
      - FEATURE_BETA_BANNER_ENABLED=False
      - KEEP_ALIVE=30

  cli:
    container_name: cli
    platform: linux/amd64
    build: platformsh-cli
    volumes:
      - media:/app/media
      - ./database_dumps:/app/database_dumps
    env_file:
      - .env

  dev:
    container_name: dev
    build:
      context: .
      dockerfile: dev/Dockerfile
    restart: always
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres

volumes:
  media:
