services:
  db:
    container_name: db
    image: postgres:16.0
    ports:
      - 5432:5432
    volumes:
      - ./database_dumps:/app/database_dumps
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres

  web:
    container_name: web
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-django-root
        IMAGE_TAG: preview
    volumes:
      - ./etna:/app/etna
      - ./config:/app/config
      - ./sass:/app/sass
      - ./scripts:/app/scripts
      - ./static:/app/static
      - ./templates:/app/templates
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - media:/media
    depends_on:
      - db
    ports:
      - 8002:8080
    command: sh /app/bash/run-dev.sh
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - RUNTIME=develop
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DATABASE_HOST=db
      - NPM_DEVELOP_COMMAND=dev
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@tna.dev
      - DEBUG_TOOLBAR_ENABLED=False
      - FEATURE_BETA_BANNER_ENABLED=False
      - KEEP_ALIVE=30
      - WAGTAILAPI_BASE_URL=http://host.docker.internal:8000

  cli:
    container_name: cli
    platform: linux/amd64
    build: platformsh-cli
    volumes:
      - media:/app/media
      - ./database_dumps:/app/database_dumps
    env_file:
      - .env

  dev:
    image: ghcr.io/nationalarchives/tna-python-dev:preview
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./:/app

volumes:
  media:
