[tool.poetry]
name = "Etna"
version = "24.05.14.33"
description = ""
authors = ["James Biggs <james.biggs@nationalarchives.gov.uk>"]

[tool.poetry.dependencies]
Django = "~5.1"
django-allauth = "~65.3"
django-birdbath = "~2.0"
django-redis = "~5.4"
django-taggit = "~6.1"
eventbrite = "~3.3"
gunicorn = "~23.0"
nh3 = "~0.2"
platformshconfig = "~2.4"
psycopg2-binary = "~2.9"
pyquery = "~2.0"
python = "^3.11"
python-magic = "~0.4"
sentry-sdk = "~2.20"
wagtail = "~6.3"
wagtail-font-awesome-svg = "~1.0"
wagtail-generic-chooser = "~0.6"
wagtailmedia = "~0.15"
wagtail-metadata = "~5.0"
nationalarchives-frontend-django = "^0.1.2a0"
wagtail-headless-preview = "0.8.0"

[tool.poetry.dev-dependencies]
black = "~24.10"
coverage = "~7.6"
django-debug-toolbar = "~5.0"
django-extensions = "~3.2"
flake8 = "~7.0"
ipdb = "~0.13"
isort = "~5.13"
mkdocs-material = "~9.5"
pymdown-extensions = "~10.12"
responses = "~0.25"
wagtail-factories = "~4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line_length = 88
target-version = ['py39']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.venv
    | __pycache__
    | _build
    | build
    | docs
    | venv
    | node_modules
  )/
)
'''
