name: Set up AWS CLI

inputs:
  aws-access-key-id:
    required: true
    type: string
  aws-secret-access-key:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    # - name: Install AWS CLI
    #   run: |
    #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #     unzip awscliv2.zip
    #     ./aws/install --update
    #     aws --version
    #   shell: bash
    - name: Configure AWS CLI
      run: |
        export AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }}
        export AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}
        aws configure --region eu-west-2 --output json
      shell: bash
