name: Clean up feature branch

on:
  delete:

jobs:
  delete:
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        id: version-tag
        uses: ./.github/actions/get-version-tag
      - name: Debug
        run: echo "Clean up Docker image ${{ vars.DOCKER_IMAGE_NAME }}:${{ steps.version-tag.outputs.VERSION }}"
      - name: Delete image
        if: ${{ steps.version-tag.outputs.VERSION }}
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ vars.DOCKER_IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version-tag.outputs.VERSION }}