name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - ohos

concurrency:
  group: cd-${{ github.ref }}

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: snok/install-poetry@v1
      - name: Check Poetry dependencies
        run: poetry show -o
      # - name: Check npm dependencies
      #   run: |
      #     npm install
      #     npm outdated
      #     npm audit

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: ./.github/actions/node-tests

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: ./.github/actions/python-tests

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: version-tag
        uses: nationalarchives/ds-docker-actions/.github/actions/get-version-tag@main
    outputs:
      version: ${{ steps.version-tag.outputs.version-tag }}

  build:
    runs-on: ubuntu-latest
    needs:
      - test-python
      - test-node
      - check-dependencies
      - version
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        uses: nationalarchives/ds-docker-actions/.github/actions/docker-build@main
        with:
          version: ${{ needs.version.outputs.version }}
          latest: ${{ github.ref == 'refs/heads/main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ vars.DOCKER_IMAGE_NAME }}
      - name: Create tag
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ needs.version.outputs.version }}',
              sha: context.sha
            })
