name: Check Migrations

on:
  pull_request:
    paths:
      - "etna/*/migrations/**"

jobs:
  check-migrations:
    name: Check Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Check migrations
        run: python .github/scripts/check_migrations.py
