name: CD - ohos (platform.sh)

on:
  workflow_dispatch:
  push:
    branches:
      - ohos
    paths:
      # Host config
      - '.plaform/**'
      - '.platform.app.yaml'
      - 'gunicorn.conf.py'
      # Python config
      - 'poetry.lock'
      - 'pyproject.toml'
      # NPM config
      - 'package.json'
      - 'package-lock.json'
      - 'webpack.config.js'
      # App changes
      - 'config/**'
      - 'sass/**'
      - 'scripts/**'
      - 'templates/**'
      - 'etna/**'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/_tests.yml
    with:
      python-version: ${{ vars.CI_PYTHON_VERSION }}
      poetry-version: ${{ vars.CI_POETRY_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: axelerant/platformsh-deploy-action@v1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_CLI_TOKEN }}
          ssh-private-key: ${{ secrets.PLATFORM_SSH_KEY }}
          force-push: true
          environment-name: ohos
